### ISSUE TITLE
should a record really be the last item in a class?

### ISSUE THREAD

**Issue by FreeApophis** [messerli-informatik-ag/code-style#57]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md

It seems like this forces private classes (this includes records) to be defined last in a class.

The idea for that is probably to reduce the clutter in the head, but a record as a helper in a class can be defined very concise, and the move the type information all to the bottom makes IMHO no sense in such a case.

```cs
private sealed record SerializerPair<TVersion, TRecord>(TVersion Version, IDeserializer<TRecord> Deserializer);
```

**Comment by tautropfli** [comment]
Lack of alternatives. Closing.
