### ISSUE TITLE
error SA1131: Constant values should appear on the right-hand side of comparisons

### ISSUE THREAD

**Issue by FreeApophis** [messerli-informatik-ag/code-style#58]
[error SA1131: Constant values should appear on the right-hand side of comparisons](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1131.md)

I get the warning with the following code.
```cs
FileSignature == value
```

I did this intentionally, because if you have the constant on the left, it is impossible to assign a value to it.
The question is, what is this rule for? constants on the left are useful!

**Comment by tautropfli** [comment]
As decided in our developer meeting we set the severity of this rule to `Info`
