### ISSUE TITLE
The change of 2.0 to 2.1 is a breaking change.

### ISSUE THREAD

**Issue by FreeApophis** [messerli-informatik-ag/code-style#67]
An update brings the new compilation error:

`error MESSERLI001: Method contains public access modifiers`

This only happens because we usually also active `TreatWarningsAsErrors`.

So what does SemVer mean with an analyzer?

**Comment by tautropfli** [comment]
I would say since `TreatWarningsAsErrors` is an explicit opt-in that adding an analyzer with default level warning is a non breaking change.
That's also how other projects treat this such as the rust compiler iirc.
